import Head from "next/head";
import Tiptap from "~/components/Tiptap";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="my-0 bg-stone-50 dark:bg-slate-900 sm:my-14">
          <div id="main" className="container mx-auto flex justify-center">
            <div className="rounded border bg-white p-10 shadow">
              <Tiptap />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export function getStaticProps() {
  return {
    props: {},
  };
}
